version: 2

sources:
  - name: staging_data
    database: HEALTHCARE_ANALYTICS
    schema: STG
    tables:
      - name: STG_PATIENT

models:
  - name: stg_patient
    description: "Staged Patient Records"
    columns:
      - name: gender
        tests:
          - accepted_values:
              arguments:
                values: ['MALE', 'FEMALE', 'OTHER']