USE ROLE ACCOUNTADMIN;
USE WAREHOUSE TRANSFORM_WH;
USE DATABASE HEALTHCARE_ANALYTICS;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT raw_csv_format
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
FIELD_DELIMITER = ',';

DESC FILE FORMAT raw_csv_format;

CREATE STAGE IF NOT EXISTS MY_RAW_STAGE
FILE_FORMAT = (FORMAT_NAME = raw_csv_format);

SHOW STAGES;